In [49]:
# imports de librerias
import pandas as pd

In [50]:
# Leo el archivo de auctions.
auctions = pd.read_csv('auctions.csv.gzip', compression='gzip')

# Leo el archivo de installs.
installs = pd.read_csv('installs.csv.gzip', compression='gzip')

# Leo el archivo de eventos.
events = pd.read_csv('events.csv.gzip', compression='gzip')

# Leo el archivo de clicks.
clicks = pd.read_csv('clicks.csv.gzip', compression='gzip')

/Users/gmontes/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (12,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [51]:
# Top 10 de cantidad de auctions por usuario.       
auctionsPerUser = auctions[['device_id']]
auctionsPerUser.rename(columns={'device_id': 'ref_hash'}, inplace=True)
auctionsPerUser['auctionsCount'] = 1
auctionsPerUser = auctionsPerUser.groupby('ref_hash').sum()
auctionsPerUser = auctionsPerUser.sort_values(by='auctionsCount', ascending=False)
auctionsPerUser.reset_index(inplace=True)
auctionsPerUserTop10 = auctionsPerUser.head(10)
auctionsPerUserTop10

/Users/gmontes/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3778: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/Users/gmontes/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

              ref_hash  auctionsCount
0   633139769114048761          27762
1  7202276635029175071          23055
2  7298861376107043945          18188
3  6302840482782120473          16400
4  5376802567578262905          16367
5  8963711959081981780          14362
6   795159065504552200          12275
7  6841615430383729819          12077
8  5384039226444052914          11632
9  3198179064438296471          11565

In [52]:
# Cantidad de installs por usuario.
installsPerUser = installs[['ref_hash', 'attributed']]
installsPerUser.rename(columns={'attributed': 'attributedInstall'}, inplace=True)
installsPerUser['attributedInstall'] = installsPerUser['attributedInstall'].astype(int)
installsPerUser['installsCount'] = 1
installsPerUser = installsPerUser.groupby('ref_hash').sum()
installsPerUser = installsPerUser.sort_values(by='installsCount', ascending=False)
installsPerUser.reset_index(inplace=True)
installsPerUserTop10 = installsPerUser.head(10)
installsPerUserTop10

/Users/gmontes/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3778: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/Users/gmontes/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/gmontes/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

              ref_hash  attributedInstall  installsCount
0  3272750442824629569                  0              4
1  5208834946313176321                  0              4
2   808602801225309575                  0              3
3  1951826604052927528                  0              3
4  5376622639905210608                  0              3
5  2457547163021424058                  0              3
6  4603142710878547974                  0              3
7  8209340170282049305                  0              3
8  1999001885916451618                  0              3
9  2515049144505739996                  0              3

In [66]:
# Cantidad de eventos por usuario.
eventsPerUser = events[['ref_hash', 'attributed']]
eventsPerUser.rename(columns={'attributed': 'attributedEvent'}, inplace=True)
eventsPerUser['attributedEvent'] = eventsPerUser['attributedEvent'].astype(int)
eventsPerUser['eventsCount'] = 1
eventsPerUser = eventsPerUser.groupby('ref_hash').sum()
eventsPerUser = eventsPerUser.sort_values(by='eventsCount', ascending=False)
eventsPerUser.reset_index(inplace=True)
eventsPerUserTop10 = eventsPerUser.head(10)
eventsPerUserTop10

/Users/gmontes/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3778: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/Users/gmontes/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/gmontes/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

              ref_hash  attributedEvent  eventsCount
0  7823950631004872496                0         2913
1  7298478026707033340                0         2822
2  5034957474698180142                0         2681
3  5724169280369284055                0         2524
4  1706781657278990931                0         2300
5   244029859389272148                0         2240
6  7526135353349769077                0         2079
7  8876061431560425145                0         2053
8    99390558091295167                0         1966
9  2514745445577342929                0         1925

In [81]:
# Cantidad de clicks por usuario.
clicksPerUser = clicks[['ref_hash']]
clicksPerUser['clicksCount'] = 1
clicksPerUser = clicksPerUser.groupby('ref_hash').sum()
clicksPerUser = clicksPerUser.sort_values(by='clicksCount', ascending=False)
clicksPerUser.reset_index(inplace=True)
clicksPerUserTop10 = clicksPerUser.head(10)
clicksPerUserTop10

/Users/gmontes/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

              ref_hash  clicksCount
0  4063522808706112974           41
1  6841615430383729819           32
2  1244272413279716745           26
3  1486699123421703687           21
4   871778630200697460           21
5  5087801386146573665           20
6   925803901826809324           17
7  5141358577301248038           16
8  5410279713092214908           16
9  6972928558719957056           16

# Top 10 de usuarios con mas auctions vs installs vs events vs clicks.

In [73]:
# Mergeo todos los dataframes que me quedaron con el de auctionsPerUserTop10.
mergedDataTopAuctions = pd.merge(auctionsPerUserTop10, installsPerUser, on='ref_hash', how='left')
mergedDataTopAuctions = pd.merge(mergedDataTopAuctions, eventsPerUser, on='ref_hash', how='left')
mergedDataTopAuctions = pd.merge(mergedDataTopAuctions, clicksPerUser, on='ref_hash', how='left')
mergedDataTopAuctions.fillna(0)

,ref_hash,auctionsCount,attributedInstall,installsCount,attributedEvent,eventsCount,clicksCount
0,633139769114048761,27762,0.0,0.0,0.0,0.0,10.0
1,7202276635029175071,23055,0.0,0.0,0.0,0.0,10.0
2,7298861376107043945,18188,0.0,0.0,0.0,0.0,12.0
3,6302840482782120473,16400,0.0,0.0,0.0,0.0,0.0
4,5376802567578262905,16367,0.0,0.0,0.0,0.0,9.0
5,8963711959081981780,14362,0.0,0.0,0.0,8.0,0.0
6,795159065504552200,12275,0.0,0.0,0.0,0.0,1.0
7,6841615430383729819,12077,0.0,0.0,0.0,0.0,32.0
8,5384039226444052914,11632,0.0,0.0,0.0,0.0,4.0
9,3198179064438296471,11565,0.0,0.0,0.0,3.0,0.0

# Top 10 de usuarios con mas installs vs auctions vs events vs clicks.

In [74]:
# Mergeo todos los dataframes que me quedaron con el de installsPerUserTop10.
mergedDataTopInstalls = pd.merge(installsPerUserTop10, auctionsPerUser, on='ref_hash', how='left')
mergedDataTopInstalls = pd.merge(mergedDataTopInstalls, eventsPerUser, on='ref_hash', how='left')
mergedDataTopInstalls = pd.merge(mergedDataTopInstalls, clicksPerUser, on='ref_hash', how='left')
mergedDataTopInstalls.fillna(0)

,ref_hash,attributedInstall,installsCount,auctionsCount,attributedEvent,eventsCount,clicksCount
0,3272750442824629569,0,4,0.0,0,951,0.0
1,5208834946313176321,0,4,0.0,0,41,0.0
2,808602801225309575,0,3,0.0,0,19,0.0
3,1951826604052927528,0,3,63.0,0,3,0.0
4,5376622639905210608,0,3,54.0,0,15,0.0
5,2457547163021424058,0,3,0.0,0,64,0.0
6,4603142710878547974,0,3,0.0,0,9,0.0
7,8209340170282049305,0,3,0.0,0,49,0.0
8,1999001885916451618,0,3,0.0,0,3,0.0
9,2515049144505739996,0,3,236.0,0,46,0.0

# Top 10 de usuarios con mas eventos vs auctions vs installs vs clicks.

In [76]:
# Mergeo todos los dataframes que me quedaron con el de eventsPerUserTop10.
mergedDataTopEvents = pd.merge(eventsPerUserTop10, installsPerUser, on='ref_hash', how='left')
mergedDataTopEvents = pd.merge(mergedDataTopEvents, auctionsPerUser, on='ref_hash', how='left')
mergedDataTopEvents = pd.merge(mergedDataTopEvents, clicksPerUser, on='ref_hash', how='left')
mergedDataTopEvents.fillna(0)

,ref_hash,attributedEvent,eventsCount,attributedInstall,installsCount,auctionsCount,clicksCount
0,7823950631004872496,0,2913,0.0,0.0,0.0,0.0
1,7298478026707033340,0,2822,0.0,0.0,2.0,0.0
2,5034957474698180142,0,2681,0.0,0.0,43.0,0.0
3,5724169280369284055,0,2524,0.0,0.0,0.0,0.0
4,1706781657278990931,0,2300,0.0,0.0,3.0,0.0
5,244029859389272148,0,2240,0.0,0.0,70.0,0.0
6,7526135353349769077,0,2079,0.0,0.0,0.0,0.0
7,8876061431560425145,0,2053,0.0,0.0,0.0,0.0
8,99390558091295167,0,1966,0.0,0.0,6.0,0.0
9,2514745445577342929,0,1925,0.0,0.0,0.0,0.0

# Top 10 de usuarios con mas clicks vs auctions vs installs vs eventos.

In [82]:
# Mergeo todos los dataframes que me quedaron con el de clicksPerUserTop10.
mergedDataTopClicks = pd.merge(clicksPerUserTop10, installsPerUser, on='ref_hash', how='left')
mergedDataTopClicks = pd.merge(mergedDataTopClicks, auctionsPerUser, on='ref_hash', how='left')
mergedDataTopClicks = pd.merge(mergedDataTopClicks, eventsPerUser, on='ref_hash', how='left')
mergedDataTopClicks.fillna(0)

,ref_hash,clicksCount,attributedInstall,installsCount,auctionsCount,attributedEvent,eventsCount
0,4063522808706112974,41,0.0,0.0,5596,0.0,0.0
1,6841615430383729819,32,0.0,0.0,12077,0.0,0.0
2,1244272413279716745,26,0.0,0.0,3297,0.0,0.0
3,1486699123421703687,21,0.0,0.0,6175,0.0,1.0
4,871778630200697460,21,0.0,0.0,1687,0.0,4.0
5,5087801386146573665,20,0.0,0.0,129,0.0,0.0
6,925803901826809324,17,0.0,0.0,8127,0.0,0.0
7,5141358577301248038,16,0.0,0.0,824,0.0,0.0
8,5410279713092214908,16,0.0,0.0,46,0.0,0.0
9,6972928558719957056,16,0.0,0.0,914,0.0,0.0